### ISSUE TITLE
How to change the CSS slightly

### ISSUE THREAD

**Issue by Serenade600** [cunhapaulo/marpstyle#1]
Hi,

Your css files for marp theme are awesome. Thanks for sharing it. 

I would like to only slightly modify it. But as a newbie of css, I met some trouble. I want to modify the looking of numbered list. It seems the related sentence is `<!-- _class: cool-list -->` in the md file, but in the corresponding css file seemingly no related description is included. I also noticed the `@import "schema";` in the css file. Do you know where to find the "schema" file?

**Comment by cunhapaulo** [comment]
Hello,

Happy it all could be useful for you.

The definition of `cool-list` can be found at `style/structure.css`. It is not my personal work as I imported it from: `https://catalin.red/css3-ordered-list-styles/` with gratitude.
Maybe browsing through the code in `style/structure.css` you find what you are looking for. Otherwise, bring your doubts here. You are welcome!
